### ISSUE TITLE
If a speaker is featured but not marked as accepted detailed speaker profile is not displaying

### ISSUE THREAD

**Issue by martinfmi** [bgjug/jprime#177] opened 2020-02-18 16:05 UTC
Steps to reproduce:

- go to speakers;
- create a new featured speaker (don't mark accepted);
- navigate to https://jprime.io/speaker/speaker_id

Screen is broken (no image and description are displayed).

**Comment by gochev** [comment] 2020-02-20 09:29
even featured speakers has to be accepted. The reason is that "accepted" means "SHOW ON THE WEBSITE" ... featured... I dont know what means :D nothing :D so ... ignore the "featured" just use accepted for everything.

**Comment by gochev** [comment] 2022-04-04 10:24
Closing this since not a defect ;) it works by design :)

**Closed by gochev** 2022-04-04 10:24 UTC
